import { drizzle } from "drizzle-orm/mysql2";
import { breeds, horseFacts } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

const breedData = [
  {
    name: "American Quarter Horse",
    slug: "american-quarter-horse",
    category: "light" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 950,
    weightMax: 1200,
    colors: ["bay", "chestnut", "black", "brown", "buckskin", "palomino", "gray", "roan"],
    distinctiveFeatures: "Medium-boned with a finely chiseled head, wide forehead, flat profile, and heavily muscled hindquarters. Known for their compact, powerful build.",
    overview: "The American Quarter Horse is the most popular breed in the United States, known for its versatility, calm temperament, and exceptional speed over short distances. Originally bred in the 1600s, it excels in western disciplines and is beloved by beginners and professionals alike.",
    physicalDescription: "Quarter Horses have a small, refined head with a straight profile, strong shoulders, and a compact body. Their most distinctive feature is their powerful hindquarters, which give them explosive acceleration. They typically stand 14-16 hands tall and weigh 950-1,200 pounds.",
    temperament: "Known for being docile, intelligent, and willing to please. Quarter Horses are calm and steady, making them excellent for beginners. They are quick learners and form strong bonds with their handlers.",
    history: "Developed in colonial America during the 1600s by crossing English Thoroughbreds with horses of Spanish origin. Named for their ability to outrun other breeds in quarter-mile races. The American Quarter Horse Association was founded in 1940 and maintains the largest breed registry in the world.",
    uses: "Western riding, ranch work, rodeo events, barrel racing, reining, cutting, trail riding, and pleasure riding. Also used in English disciplines like jumping and dressage.",
    careRequirements: "Relatively easy keepers that thrive on quality hay and pasture. Regular grooming, hoof care, and dental checkups are essential. They adapt well to various climates.",
    healthConsiderations: "May be prone to hyperkalemic periodic paralysis (HYPP) in certain bloodlines. Also watch for polysaccharide storage myopathy (PSSM) and hereditary equine regional dermal asthenia (HERDA).",
    feedingNotes: "Easy keepers that can become overweight if overfed. A diet of quality hay, limited grain, and access to fresh water is typically sufficient.",
    lifespan: "25-30 years",
    origin: "United States",
    popularity: "common" as const,
    keywords: ["quarter horse", "western", "ranch", "muscular", "compact", "beginner friendly", "versatile", "rodeo"],
  },
  {
    name: "Arabian",
    slug: "arabian",
    category: "light" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 800,
    weightMax: 1000,
    colors: ["bay", "gray", "chestnut", "black", "roan"],
    distinctiveFeatures: "Distinctive dished (concave) face profile, large expressive eyes, arched neck, and high tail carriage. Refined, elegant appearance with a compact body.",
    overview: "The Arabian is one of the oldest and most influential horse breeds in the world, with a lineage dating back over 4,500 years. Known for their beauty, endurance, and spirited yet gentle nature, Arabians have contributed to the development of nearly every modern light horse breed.",
    physicalDescription: "Arabians have a distinctive wedge-shaped head with a dished profile, large eyes, and small curved ears. They have a naturally high tail carriage, a short back with one fewer vertebra than other breeds, and a compact, refined body. They typically stand 14.1-15.1 hands.",
    temperament: "Intelligent, alert, and spirited with a gentle, affectionate nature. They are highly sensitive and form strong bonds with their owners. While spirited, they are not typically aggressive and respond well to patient training.",
    history: "Originated in the Arabian Peninsula, where Bedouin tribes selectively bred them for endurance, intelligence, and beauty. They were prized possessions and often lived with their families. Arabians were introduced to Europe through trade and conquest, influencing breeds worldwide.",
    uses: "Endurance riding (where they dominate), dressage, show, pleasure riding, and trail riding. Their stamina makes them excellent for long-distance events.",
    careRequirements: "Generally hardy and require less food than other breeds of similar size. Regular grooming maintains their beautiful coat. They thrive in hot climates but adapt to various environments.",
    healthConsiderations: "Generally healthy but may be prone to severe combined immunodeficiency (SCID), cerebellar abiotrophy (CA), and lavender foal syndrome in certain bloodlines. Genetic testing is recommended.",
    feedingNotes: "Efficient metabolizers that require less feed than many breeds. Overfeeding can lead to obesity. Quality hay and limited grain are usually sufficient.",
    lifespan: "25-30 years",
    origin: "Arabian Peninsula",
    popularity: "common" as const,
    keywords: ["arabian", "dished face", "endurance", "elegant", "spirited", "ancient", "high tail", "refined"],
  },
  {
    name: "Thoroughbred",
    slug: "thoroughbred",
    category: "light" as const,
    heightMin: 15,
    heightMax: 17,
    weightMin: 1000,
    weightMax: 1300,
    colors: ["bay", "brown", "chestnut", "black", "gray"],
    distinctiveFeatures: "Tall, lean athletic build with long legs, deep chest, and refined head. Built for speed with long, flat muscles and a streamlined appearance.",
    overview: "The Thoroughbred is the premier racing horse, known for its speed, agility, and competitive spirit. Developed in 17th-18th century England, they are considered 'hot-blooded' horses with high energy and sensitivity. Beyond racing, they excel in many equestrian sports.",
    physicalDescription: "Thoroughbreds have a refined, elegant appearance with a long neck, high withers, deep chest, and long legs. They are tall (15-17 hands) and lean, with well-defined muscles. Their heads are refined with large, intelligent eyes.",
    temperament: "Hot-blooded, spirited, and sensitive. They are intelligent and athletic but can be high-strung. Best suited for experienced handlers who can channel their energy positively.",
    history: "Developed in 17th-18th century England by crossing native mares with imported Arabian, Barb, and Turkoman stallions. All modern Thoroughbreds trace to three foundation sires: the Byerly Turk, Darley Arabian, and Godolphin Arabian.",
    uses: "Horse racing, show jumping, dressage, eventing, polo, and fox hunting. Many retired racehorses are retrained for other disciplines.",
    careRequirements: "Require more attention than some breeds due to their sensitive nature. Regular exercise is essential. They may need blankets in cold weather due to their thin skin.",
    healthConsiderations: "Prone to bleeding from the lungs during intense exercise (EIPH), bone and joint issues, and gastric ulcers. Their thin skin makes them susceptible to cuts and scrapes.",
    feedingNotes: "High metabolisms require more feed than many breeds. Quality hay, grain, and supplements support their athletic demands. Monitor weight carefully.",
    lifespan: "25-35 years",
    origin: "England",
    popularity: "common" as const,
    keywords: ["thoroughbred", "racing", "tall", "lean", "athletic", "fast", "hot-blooded", "sport horse"],
  },
  {
    name: "Appaloosa",
    slug: "appaloosa",
    category: "light" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 950,
    weightMax: 1200,
    colors: ["spotted", "blanket", "leopard", "snowflake", "few spot", "frost"],
    distinctiveFeatures: "Distinctive spotted coat patterns, mottled skin around eyes and muzzle, striped hooves, and visible white sclera around the eyes.",
    overview: "The Appaloosa is famous for its colorful spotted coat pattern and is one of the most recognizable horse breeds. Developed by the Nez Perce people, they are versatile, hardy horses known for their endurance and willing temperament.",
    physicalDescription: "Appaloosas have a compact, muscular build similar to Quarter Horses. Their most distinctive features are their spotted coat patterns, which can include blanket, leopard, snowflake, and other variations. They have mottled skin, striped hooves, and visible white sclera.",
    temperament: "Intelligent, independent, and versatile. They are generally calm and willing but can be stubborn. They form strong bonds with their handlers and are known for their hardiness.",
    history: "Developed by the Nez Perce Native Americans in the Pacific Northwest, who selectively bred for color, speed, and endurance. Named after the Palouse River region. Nearly went extinct after the Nez Perce War but was revived in the 20th century.",
    uses: "Western riding, trail riding, endurance, show, and ranch work. Their versatility makes them suitable for many disciplines.",
    careRequirements: "Hardy and adaptable. Spotted horses with pink skin may need sun protection. Regular grooming maintains their distinctive coat.",
    healthConsiderations: "May be prone to equine recurrent uveitis (moon blindness) and congenital stationary night blindness. Pink-skinned areas are susceptible to sunburn.",
    feedingNotes: "Generally easy keepers. Standard diet of quality hay and appropriate grain. Monitor for weight gain.",
    lifespan: "25-30 years",
    origin: "United States (Nez Perce)",
    popularity: "common" as const,
    keywords: ["appaloosa", "spotted", "leopard", "blanket", "striped hooves", "nez perce", "colorful", "western"],
  },
  {
    name: "Morgan",
    slug: "morgan",
    category: "light" as const,
    heightMin: 14,
    heightMax: 15,
    weightMin: 900,
    weightMax: 1100,
    colors: ["bay", "black", "chestnut", "brown"],
    distinctiveFeatures: "Compact, refined build with an arched, crested neck, expressive eyes, small ears, and proud carriage. Known for their elegant appearance despite smaller size.",
    overview: "The Morgan is one of the earliest American horse breeds, known for its versatility, strength, and elegant appearance. All Morgans trace back to a single foundation sire named Figure (later called Justin Morgan). They excel in both English and Western disciplines.",
    physicalDescription: "Morgans are compact and muscular with a refined head, expressive eyes, and small, alert ears. Their most distinctive feature is their beautifully arched, crested neck. They typically stand 14.1-15.2 hands and have a proud, animated way of moving.",
    temperament: "Intelligent, willing, and people-oriented. Morgans are known for their friendly, cooperative nature and strong work ethic. They are versatile and eager to please.",
    history: "All Morgans descend from a single stallion named Figure, born in 1789 in Massachusetts. Later known as Justin Morgan after his owner, this remarkable horse could outwork, outrun, and outwalk other horses. The breed became Vermont's state animal.",
    uses: "Driving, pleasure riding, dressage, western, trail riding, and therapeutic riding. Their versatility makes them suitable for almost any discipline.",
    careRequirements: "Easy keepers that require minimal special care. Regular grooming, hoof care, and exercise keep them healthy and happy.",
    healthConsiderations: "Generally healthy breed. Some lines may carry genes for type 1 polysaccharide storage myopathy (PSSM1). Genetic testing is available.",
    feedingNotes: "Very easy keepers prone to weight gain. Require less feed than many breeds. Monitor carefully to prevent obesity.",
    lifespan: "25-30 years",
    origin: "United States (Vermont)",
    popularity: "moderate" as const,
    keywords: ["morgan", "crested neck", "compact", "versatile", "elegant", "vermont", "driving", "all-around"],
  },
  {
    name: "Paint Horse",
    slug: "paint-horse",
    category: "light" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 950,
    weightMax: 1200,
    colors: ["tobiano", "overo", "tovero", "solid"],
    distinctiveFeatures: "Large patches of white and another color (usually black, bay, or chestnut) in distinctive patterns. Stock horse build similar to Quarter Horses.",
    overview: "The American Paint Horse combines the colorful coat patterns of a pinto with the conformation of a western stock horse. They share bloodlines with Quarter Horses and Thoroughbreds, offering the same versatility with eye-catching color.",
    physicalDescription: "Paint Horses have a stock horse build with powerful hindquarters, strong shoulders, and a refined head. Their coat patterns include tobiano (white crossing the back), overo (white not crossing the back), and tovero (combination). They stand 14-16 hands.",
    temperament: "Calm, intelligent, and athletic. Like Quarter Horses, they are known for their willing, cooperative nature and make excellent family horses.",
    history: "Descended from horses brought to the Americas by Spanish explorers. Native Americans prized spotted horses. The American Paint Horse Association was founded in 1965 to register horses with Quarter Horse or Thoroughbred bloodlines and pinto coloring.",
    uses: "Western riding, ranch work, trail riding, show, and pleasure riding. Excel in the same disciplines as Quarter Horses.",
    careRequirements: "Similar to Quarter Horses. Easy keepers that adapt well to various environments. Areas with pink skin may need sun protection.",
    healthConsiderations: "May carry lethal white overo syndrome (LWOS) gene. Genetic testing recommended before breeding. Otherwise similar health profile to Quarter Horses.",
    feedingNotes: "Easy keepers that can become overweight. Standard diet of quality hay with limited grain as needed.",
    lifespan: "25-30 years",
    origin: "United States",
    popularity: "common" as const,
    keywords: ["paint", "pinto", "tobiano", "overo", "spotted", "colorful", "stock horse", "western"],
  },
  {
    name: "Clydesdale",
    slug: "clydesdale",
    category: "draft" as const,
    heightMin: 16,
    heightMax: 18,
    weightMin: 1800,
    weightMax: 2200,
    colors: ["bay", "brown", "black", "roan"],
    distinctiveFeatures: "Massive size with abundant feathering on lower legs, white facial markings, and four white stockings. High-stepping, flashy action.",
    overview: "The Clydesdale is a Scottish draft breed famous for its size, strength, and the distinctive feathering on its legs. Made famous by the Budweiser commercials, these gentle giants are known for their calm temperament and flashy appearance.",
    physicalDescription: "Clydesdales are tall (16-18 hands) and heavy (1,800-2,200 lbs) with a broad forehead, arched neck, and sloping shoulders. Their most distinctive features are the long, silky feathering on their lower legs and their high-stepping gait.",
    temperament: "Despite their imposing size, Clydesdales are known as 'gentle giants.' They are calm, intelligent, and willing workers with a kind disposition.",
    history: "Developed in the Clydesdale district of Scotland in the 18th century for farm and industrial work. Imported to North America in the mid-1800s. The Budweiser Clydesdales have made them one of the most recognized breeds worldwide.",
    uses: "Driving, parades, shows, logging, and pleasure riding. Their calm nature makes them suitable for therapeutic riding programs.",
    careRequirements: "Require more feed and space than light horses. Feathering needs regular cleaning and care to prevent skin issues. Need larger stalls and equipment.",
    healthConsiderations: "May be prone to chronic progressive lymphedema affecting the lower legs. Feathering can harbor bacteria and fungi if not properly maintained.",
    feedingNotes: "Require significantly more feed than light horses due to their size. Quality hay, grain, and supplements support their nutritional needs.",
    lifespan: "20-25 years",
    origin: "Scotland",
    popularity: "moderate" as const,
    keywords: ["clydesdale", "draft", "feathered", "giant", "scottish", "budweiser", "gentle giant", "heavy"],
  },
  {
    name: "Friesian",
    slug: "friesian",
    category: "warmblood" as const,
    heightMin: 15,
    heightMax: 17,
    weightMin: 1200,
    weightMax: 1400,
    colors: ["black"],
    distinctiveFeatures: "Always black with no white markings, luxurious long mane and tail, feathered fetlocks, and elegant arched neck. Striking, noble appearance.",
    overview: "The Friesian is a stunning black horse breed from the Netherlands, known for its elegant appearance, flowing mane and tail, and graceful movement. Originally a war horse, today they excel in dressage and driving.",
    physicalDescription: "Friesians are always black (though rare chestnuts occur) with no white markings allowed for registration. They have a refined head, arched neck, compact muscular body, and feathered fetlocks. Their long, thick mane and tail are their crowning glory.",
    temperament: "Willing, gentle, and intelligent. Friesians are known for their calm, steady nature combined with an eagerness to work. They bond closely with their handlers.",
    history: "One of Europe's oldest breeds, originating in Friesland (Netherlands). Used as war horses in medieval times, they later became popular carriage horses. Nearly went extinct in the early 20th century but was saved by dedicated breeders.",
    uses: "Dressage, driving, pleasure riding, and film/television work. Their dramatic appearance makes them popular in movies and shows.",
    careRequirements: "Require regular grooming to maintain their luxurious mane, tail, and feathers. May need more care in hot climates. Feathering should be kept clean and dry.",
    healthConsiderations: "May be prone to dwarfism, hydrocephalus, and aortic rupture due to limited genetic diversity. Megaesophagus and retained placenta are also concerns.",
    feedingNotes: "Moderate keepers. Quality hay and appropriate grain maintain their condition. Monitor weight as they can become overweight.",
    lifespan: "16-20 years",
    origin: "Netherlands (Friesland)",
    popularity: "moderate" as const,
    keywords: ["friesian", "black", "elegant", "feathered", "mane", "dressage", "dutch", "noble"],
  },
  {
    name: "Tennessee Walking Horse",
    slug: "tennessee-walking-horse",
    category: "gaited" as const,
    heightMin: 15,
    heightMax: 17,
    weightMin: 900,
    weightMax: 1200,
    colors: ["black", "bay", "chestnut", "palomino", "roan", "gray", "spotted"],
    distinctiveFeatures: "Smooth, gliding four-beat running walk gait. Long, sloping shoulders, refined head, and naturally high head carriage.",
    overview: "The Tennessee Walking Horse is famous for its smooth, comfortable gaits that make it a pleasure to ride for hours. Developed in the southern United States, they are known for their calm temperament and natural four-beat running walk.",
    physicalDescription: "Tennessee Walkers have a refined head, long neck, sloping shoulders, and a short back. They are tall (15-17 hands) with a naturally high head carriage. Their most distinctive feature is their smooth, gliding gait.",
    temperament: "Calm, gentle, and willing. Known as the 'Gentleman of the Horse World' for their kind, docile nature. They are patient and make excellent family horses.",
    history: "Developed in middle Tennessee in the late 1800s from Narragansett Pacers, Standardbreds, Morgans, and Thoroughbreds. Plantation owners prized them for their smooth gaits during long days of overseeing crops.",
    uses: "Trail riding, pleasure riding, show, and therapeutic riding. Their smooth gaits make them ideal for riders with back problems or those who want comfortable long rides.",
    careRequirements: "Generally easy keepers. Standard care with attention to hoof health. Some show horses require specialized shoeing.",
    healthConsiderations: "Generally healthy. The breed has faced controversy over 'soring' practices in some show circles, which is now illegal.",
    feedingNotes: "Easy to moderate keepers. Standard diet of quality hay and grain as needed. Monitor weight.",
    lifespan: "28-30 years",
    origin: "United States (Tennessee)",
    popularity: "moderate" as const,
    keywords: ["tennessee walker", "gaited", "smooth", "running walk", "comfortable", "trail", "plantation", "gentle"],
  },
  {
    name: "Mustang",
    slug: "mustang",
    category: "light" as const,
    heightMin: 13,
    heightMax: 15,
    weightMin: 700,
    weightMax: 1000,
    colors: ["bay", "black", "chestnut", "gray", "roan", "dun", "palomino", "pinto"],
    distinctiveFeatures: "Hardy, compact build with strong hooves. Variable appearance due to mixed heritage. Often have primitive markings like dorsal stripes.",
    overview: "The Mustang is a free-roaming horse of the American West, descended from horses brought by Spanish explorers. Known for their hardiness, intelligence, and sure-footedness, adopted Mustangs make loyal, versatile partners.",
    physicalDescription: "Mustangs vary in appearance due to their mixed heritage but are generally compact and hardy, standing 13-15 hands. They have strong hooves, good bone, and often display primitive markings like dorsal stripes and leg barring.",
    temperament: "Intelligent, independent, and wary initially but form strong bonds once trust is established. They are survivors with strong self-preservation instincts.",
    history: "Descended from horses brought to the Americas by Spanish conquistadors in the 1500s. Escaped and released horses formed wild herds. The Bureau of Land Management manages wild herds and offers horses for adoption.",
    uses: "Trail riding, endurance, ranch work, and competitive events. Their hardiness and sure-footedness make them excellent trail horses.",
    careRequirements: "Hardy and require minimal special care once gentled. Their strong hooves often need less frequent farrier visits. May need time to adjust to domestic life.",
    healthConsiderations: "Generally very healthy due to natural selection. Strong hooves and constitutions. May need patience during initial training.",
    feedingNotes: "Very easy keepers adapted to sparse forage. Can become overweight on rich pasture. Monitor carefully and limit access to lush grass.",
    lifespan: "25-30 years",
    origin: "United States (feral)",
    popularity: "moderate" as const,
    keywords: ["mustang", "wild", "feral", "hardy", "spanish", "western", "sure-footed", "primitive"],
  },
  {
    name: "Percheron",
    slug: "percheron",
    category: "draft" as const,
    heightMin: 16,
    heightMax: 18,
    weightMin: 1800,
    weightMax: 2600,
    colors: ["gray", "black"],
    distinctiveFeatures: "Massive size with clean legs (minimal feathering), refined head for a draft breed, and elegant movement. Usually gray or black.",
    overview: "The Percheron is a French draft breed known for its strength, intelligence, and willingness to work. Unlike other draft breeds, they have minimal leg feathering and more refined features, showing Arabian influence in their ancestry.",
    physicalDescription: "Percherons are large (16-18 hands, 1,800-2,600 lbs) with a refined head, arched neck, and clean legs with minimal feathering. They are usually gray or black. Their movement is more elegant than typical draft breeds.",
    temperament: "Intelligent, willing, and calm. Percherons are known for their good nature and eagerness to please. They are versatile and adaptable.",
    history: "Developed in the Perche region of France, with Arabian blood introduced during the Crusades. They became popular in America for farm work and hauling. Today they are used for driving, riding, and crossbreeding.",
    uses: "Driving, farm work, logging, parades, and riding. Their cleaner legs and more refined build make them popular for crossing with lighter breeds.",
    careRequirements: "Require more feed and space than light horses but less leg care than heavily feathered drafts. Regular grooming and hoof care essential.",
    healthConsiderations: "May be prone to equine polysaccharide storage myopathy (EPSM). Generally healthy and long-lived for a draft breed.",
    feedingNotes: "Require substantial feed due to size. Quality hay and grain support their nutritional needs. Monitor for weight gain.",
    lifespan: "25-30 years",
    origin: "France",
    popularity: "moderate" as const,
    keywords: ["percheron", "draft", "french", "gray", "black", "clean legs", "elegant", "heavy"],
  },
  {
    name: "Shire",
    slug: "shire",
    category: "draft" as const,
    heightMin: 16,
    heightMax: 19,
    weightMin: 1800,
    weightMax: 2400,
    colors: ["black", "bay", "brown", "gray"],
    distinctiveFeatures: "One of the largest horse breeds with abundant leg feathering, Roman nose, and massive build. Can exceed 19 hands.",
    overview: "The Shire is one of the largest and strongest horse breeds in the world. Originating in England, these gentle giants were bred for heavy farm and industrial work. Despite their massive size, they are known for their docile, patient temperament.",
    physicalDescription: "Shires are massive horses, often exceeding 17 hands and weighing over 2,000 lbs. They have a long, lean head (often with a Roman nose), long arched neck, and abundant feathering on their lower legs. Colors include black, bay, brown, and gray.",
    temperament: "Extremely gentle and patient despite their size. Shires are calm, willing workers with a docile disposition. They are easy to handle and train.",
    history: "Developed in England from the Great Horse of medieval times. Used for farm work, pulling brewery wagons, and heavy hauling. The breed declined with mechanization but is now preserved by enthusiasts.",
    uses: "Driving, farm work, shows, and promotional events. Their calm nature makes them suitable for parades and public appearances.",
    careRequirements: "Require substantial space, feed, and larger equipment. Feathering needs regular care to prevent skin issues. Need experienced handlers due to size.",
    healthConsiderations: "May be prone to chronic progressive lymphedema and polysaccharide storage myopathy. Feathering requires attention to prevent dermatitis.",
    feedingNotes: "Require large amounts of quality feed. Hay, grain, and supplements support their massive frames. Monitor for weight issues.",
    lifespan: "20-25 years",
    origin: "England",
    popularity: "rare" as const,
    keywords: ["shire", "draft", "largest", "feathered", "english", "gentle giant", "massive", "heavy"],
  },
  {
    name: "Hanoverian",
    slug: "hanoverian",
    category: "warmblood" as const,
    heightMin: 16,
    heightMax: 17,
    weightMin: 1200,
    weightMax: 1400,
    colors: ["bay", "black", "chestnut", "gray"],
    distinctiveFeatures: "Athletic warmblood build with powerful hindquarters, elegant movement, and refined head. Bred for Olympic-level competition.",
    overview: "The Hanoverian is one of the most successful warmblood breeds in international competition. Developed in Germany, they excel in dressage, show jumping, and eventing, combining athleticism with a trainable temperament.",
    physicalDescription: "Hanoverians are tall (16-17 hands) with an athletic build, powerful hindquarters, and elegant movement. They have a refined head, long neck, and strong back. Their conformation is ideal for upper-level sport horse competition.",
    temperament: "Intelligent, willing, and athletic. Hanoverians have good temperaments for competition, being trainable yet forward-thinking. They are sensitive and responsive to their riders.",
    history: "Developed in the Hanover region of Germany beginning in 1735. Originally bred as carriage and military horses, they were refined after WWII for sport horse competition. Now one of the most successful breeds in Olympic equestrian events.",
    uses: "Dressage, show jumping, eventing, and combined driving. They dominate international competition in these disciplines.",
    careRequirements: "Require quality nutrition and regular exercise to maintain their athletic condition. Standard grooming and hoof care. May need specialized training.",
    healthConsiderations: "Generally healthy. May be prone to osteochondrosis (OCD) in young horses. Careful breeding practices have reduced genetic issues.",
    feedingNotes: "Athletic horses requiring quality nutrition. Hay, grain, and supplements support their training demands. Adjust feed to workload.",
    lifespan: "25-30 years",
    origin: "Germany",
    popularity: "common" as const,
    keywords: ["hanoverian", "warmblood", "sport horse", "dressage", "jumping", "german", "olympic", "athletic"],
  },
  {
    name: "Shetland Pony",
    slug: "shetland-pony",
    category: "pony" as const,
    heightMin: 7,
    heightMax: 11,
    weightMin: 400,
    weightMax: 450,
    colors: ["black", "bay", "chestnut", "gray", "palomino", "pinto"],
    distinctiveFeatures: "Very small but sturdy build, thick double coat, abundant mane and tail, and short legs. Incredibly strong for their size.",
    overview: "The Shetland Pony is one of the smallest and hardiest pony breeds. Originating from the harsh Shetland Islands of Scotland, they are incredibly strong for their size and have been used for everything from coal mining to children's mounts.",
    physicalDescription: "Shetlands are very small (under 11.2 hands) but sturdy and well-proportioned. They have a thick double coat, abundant mane and tail, short legs, and a broad body. Their small size belies their remarkable strength.",
    temperament: "Intelligent and hardy but can be stubborn and willful. They are generally good with children but need consistent handling. Their cleverness can lead to mischief.",
    history: "Developed on the Shetland Islands off Scotland, where harsh conditions created an extremely hardy pony. Used in coal mines in the 1800s due to their small size and strength. Now popular as children's ponies and driving ponies.",
    uses: "Children's mount, driving, therapy programs, and companion animal. Their small size makes them suitable for young riders.",
    careRequirements: "Very hardy and easy keepers. Their thick coat needs regular grooming. Prone to obesity if overfed. Need firm, consistent handling.",
    healthConsiderations: "Prone to laminitis and obesity. May develop Cushing's disease. Their small size means they need carefully monitored diets.",
    feedingNotes: "Extremely easy keepers that can founder on rich pasture. Limited hay and minimal or no grain. Grazing muzzles often necessary.",
    lifespan: "25-30+ years",
    origin: "Scotland (Shetland Islands)",
    popularity: "common" as const,
    keywords: ["shetland", "pony", "small", "hardy", "children", "thick coat", "sturdy", "miniature"],
  },
  {
    name: "Welsh Pony",
    slug: "welsh-pony",
    category: "pony" as const,
    heightMin: 12,
    heightMax: 14,
    weightMin: 500,
    weightMax: 700,
    colors: ["gray", "bay", "chestnut", "black", "palomino", "cream"],
    distinctiveFeatures: "Refined, elegant appearance with dished face showing Arabian influence. Four sections (A, B, C, D) varying in size. Athletic and beautiful.",
    overview: "The Welsh Pony is one of the most beautiful and versatile pony breeds, showing Arabian influence in its refined features. Divided into four sections by size, Welsh Ponies excel in showing, driving, and as children's mounts.",
    physicalDescription: "Welsh Ponies have a refined, elegant appearance with a slightly dished face, large eyes, and small ears. They come in four sections: A (under 12.2h), B (under 13.2h), C (under 13.2h, cob type), and D (over 13.2h). All are well-proportioned and athletic.",
    temperament: "Intelligent, spirited, and willing. Welsh Ponies are known for their good temperaments and versatility. They are athletic and forward-thinking but generally manageable.",
    history: "Developed in Wales over centuries, with Arabian blood introduced to refine the breed. Used for farm work, mining, and transportation. Now popular worldwide for showing and as children's ponies.",
    uses: "Showing, driving, children's hunter/jumper, dressage, and pleasure riding. Their versatility makes them suitable for many disciplines.",
    careRequirements: "Generally easy keepers. Regular grooming maintains their beautiful appearance. Standard pony care with attention to weight management.",
    healthConsiderations: "Generally healthy. Like many ponies, prone to laminitis if overfed. Monitor weight carefully.",
    feedingNotes: "Easy keepers that can become overweight. Limited hay and minimal grain. Monitor grazing on rich pasture.",
    lifespan: "25-30 years",
    origin: "Wales",
    popularity: "common" as const,
    keywords: ["welsh", "pony", "elegant", "refined", "children", "show", "driving", "arabian influence"],
  },
  {
    name: "Paso Fino",
    slug: "paso-fino",
    category: "gaited" as const,
    heightMin: 13,
    heightMax: 15,
    weightMin: 700,
    weightMax: 1000,
    colors: ["bay", "chestnut", "black", "gray", "palomino", "pinto"],
    distinctiveFeatures: "Smooth, natural four-beat lateral gait performed at varying speeds. Refined, elegant appearance with proud carriage and animated movement.",
    overview: "The Paso Fino is a naturally gaited breed from Latin America known for its incredibly smooth, comfortable ride. Their distinctive gait, performed from birth, makes them popular for pleasure riding and showing.",
    physicalDescription: "Paso Finos are refined and elegant, typically standing 13-15.2 hands. They have a refined head, arched neck, and compact body. Their movement is animated and proud, with the distinctive paso fino gait being their hallmark.",
    temperament: "Spirited yet gentle, willing and people-oriented. Paso Finos are known for their 'brio' - a combination of spirit, willingness, and responsiveness. They bond closely with their handlers.",
    history: "Developed in Latin America from Spanish horses brought by conquistadors. The breed was refined in Puerto Rico, Colombia, and other countries. The smooth gait was prized for comfortable travel over rough terrain.",
    uses: "Pleasure riding, trail riding, showing, and endurance. Their smooth gait makes them ideal for riders wanting comfortable long rides.",
    careRequirements: "Generally easy keepers. Standard care with attention to hoof health. Their gait is natural and doesn't require special training.",
    healthConsiderations: "Generally healthy. May be prone to degenerative suspensory ligament desmitis (DSLD). Otherwise robust.",
    feedingNotes: "Easy to moderate keepers. Standard diet of quality hay and grain as needed. Monitor weight.",
    lifespan: "25-30 years",
    origin: "Latin America (Puerto Rico, Colombia)",
    popularity: "moderate" as const,
    keywords: ["paso fino", "gaited", "smooth", "latin", "spanish", "elegant", "brio", "comfortable"],
  },
  {
    name: "Miniature Horse",
    slug: "miniature-horse",
    category: "pony" as const,
    heightMin: 7,
    heightMax: 9,
    weightMin: 150,
    weightMax: 350,
    colors: ["all colors"],
    distinctiveFeatures: "Extremely small size (under 34-38 inches depending on registry) with horse proportions rather than pony build. Refined appearance.",
    overview: "Miniature Horses are bred to be small versions of full-sized horses, maintaining horse proportions rather than the stocky build of ponies. They are popular as companion animals, therapy horses, and show horses.",
    physicalDescription: "Miniature Horses stand under 34-38 inches (depending on registry) and weigh 150-350 lbs. Unlike ponies, they have refined, horse-like proportions with a balanced head, neck, and body. They come in all colors and patterns.",
    temperament: "Friendly, curious, and intelligent. Miniature Horses are generally gentle and enjoy human interaction. They can be trained for driving and as guide animals.",
    history: "Developed through selective breeding of small horses over centuries. Originally bred as pets for European nobility. In America, they were used in coal mines. Now popular as companions and therapy animals.",
    uses: "Companion animal, therapy work, driving, showing, and as guide animals for the visually impaired. Too small to ride except by very small children.",
    careRequirements: "Require careful management due to their small size. Prone to obesity and dental issues. Need appropriately sized equipment and facilities.",
    healthConsiderations: "Prone to obesity, dental problems, and hyperlipemia. Dwarfism can cause health issues. Careful breeding and management essential.",
    feedingNotes: "Very easy keepers that can quickly become obese. Very limited hay and no grain for most. Grazing muzzles often necessary.",
    lifespan: "25-35 years",
    origin: "Europe/United States",
    popularity: "common" as const,
    keywords: ["miniature", "tiny", "small", "companion", "therapy", "guide", "pet", "refined"],
  },
  {
    name: "Andalusian",
    slug: "andalusian",
    category: "light" as const,
    heightMin: 15,
    heightMax: 16,
    weightMin: 1000,
    weightMax: 1200,
    colors: ["gray", "bay", "black"],
    distinctiveFeatures: "Elegant, baroque appearance with long, flowing mane and tail, arched neck, and proud carriage. Known for collection and elevated movement.",
    overview: "The Andalusian, also known as the Pure Spanish Horse (PRE), is one of the oldest and most influential breeds. Known for their beauty, intelligence, and athletic ability, they excel in classical dressage and have influenced many other breeds.",
    physicalDescription: "Andalusians are elegant horses standing 15-16.2 hands with a strong, compact body, arched neck, and long, flowing mane and tail. Most are gray, though bay and black occur. Their movement is elevated and collected.",
    temperament: "Intelligent, sensitive, and willing. Andalusians are known for their docile nature combined with spirit and presence. They are eager to please and form strong bonds with handlers.",
    history: "Developed on the Iberian Peninsula over thousands of years. Prized by nobility and used as war horses. They influenced the development of many breeds including Lipizzans, Friesians, and most American breeds.",
    uses: "Classical dressage, driving, bullfighting, movies, and pleasure riding. Their collection and presence make them ideal for high school dressage movements.",
    careRequirements: "Moderate keepers requiring standard care. Their long mane and tail need regular grooming. Generally adaptable to various climates.",
    healthConsiderations: "May be prone to laminitis and inguinal hernias. Some lines carry genes for immune-mediated conditions. Generally healthy.",
    feedingNotes: "Moderate keepers. Quality hay and appropriate grain maintain condition. Monitor for weight gain.",
    lifespan: "25-30 years",
    origin: "Spain",
    popularity: "moderate" as const,
    keywords: ["andalusian", "spanish", "PRE", "baroque", "dressage", "elegant", "gray", "classical"],
  },
  {
    name: "Icelandic Horse",
    slug: "icelandic-horse",
    category: "gaited" as const,
    heightMin: 13,
    heightMax: 14,
    weightMin: 730,
    weightMax: 840,
    colors: ["all colors", "over 40 color combinations"],
    distinctiveFeatures: "Small but sturdy build with thick double coat, two unique gaits (tölt and flying pace), and remarkable hardiness. Never called a pony despite size.",
    overview: "The Icelandic Horse is a unique breed that has remained pure for over 1,000 years due to Iceland's isolation. Despite their small size, they are always called horses, never ponies. They are known for their five gaits and incredible hardiness.",
    physicalDescription: "Icelandic Horses are small (13-14 hands) but sturdy with a thick double coat, abundant mane and tail, and strong build. They come in over 40 color combinations. Despite their size, they can easily carry adult riders.",
    temperament: "Friendly, curious, and willing. Icelandic Horses are known for their good temperaments and sure-footedness. They are confident and rarely spook.",
    history: "Brought to Iceland by Vikings around 900 AD. Iceland banned horse imports in 982 AD, keeping the breed pure. They developed unique gaits and extreme hardiness in Iceland's harsh environment.",
    uses: "Pleasure riding, trail riding, competition (including tölt and pace races), and therapeutic riding. Their smooth gaits make them comfortable for long rides.",
    careRequirements: "Very hardy and easy keepers. Their thick coat needs minimal grooming. They must never be exposed to horses from other countries due to lack of disease immunity.",
    healthConsiderations: "Generally very healthy due to isolation. Have no immunity to many common equine diseases, so must never contact horses from outside Iceland.",
    feedingNotes: "Very easy keepers adapted to sparse Icelandic forage. Can become obese on rich pasture. Limited hay and minimal grain.",
    lifespan: "25-30+ years",
    origin: "Iceland",
    popularity: "moderate" as const,
    keywords: ["icelandic", "gaited", "tölt", "hardy", "viking", "five gaits", "small", "sturdy"],
  },
  {
    name: "Belgian Draft",
    slug: "belgian-draft",
    category: "draft" as const,
    heightMin: 16,
    heightMax: 18,
    weightMin: 1800,
    weightMax: 2200,
    colors: ["chestnut", "roan", "sorrel", "bay"],
    distinctiveFeatures: "Massive, muscular build with relatively short legs, thick neck, and powerful hindquarters. Usually chestnut or roan with flaxen mane and tail.",
    overview: "The Belgian Draft is one of the strongest horse breeds, known for its incredible pulling power and gentle disposition. Originally from Belgium, they are now the most popular draft breed in America.",
    physicalDescription: "Belgians are massive horses (16-18 hands, 1,800-2,200 lbs) with a compact, muscular build. They have a relatively small head, short thick neck, and powerful body. Most are chestnut or roan with a flaxen mane and tail.",
    temperament: "Extremely gentle, willing, and easy to handle. Belgians are known for their calm, docile nature and strong work ethic. They are patient and forgiving.",
    history: "Developed in Belgium's Brabant region. Imported to America in the late 1800s. American Belgians were bred lighter and taller than European Brabants. Now the most numerous draft breed in the US.",
    uses: "Farm work, logging, pulling competitions, driving, and pleasure riding. Their strength makes them ideal for heavy work.",
    careRequirements: "Require substantial feed and space. Generally easy to handle despite size. Standard draft horse care with attention to hoof health.",
    healthConsiderations: "May be prone to junctional epidermolysis bullosa (JEB) and chronic progressive lymphedema. Generally healthy and long-lived.",
    feedingNotes: "Require large amounts of quality feed. Hay and grain support their size and work demands. Monitor for appropriate weight.",
    lifespan: "20-25 years",
    origin: "Belgium",
    popularity: "common" as const,
    keywords: ["belgian", "draft", "chestnut", "roan", "pulling", "strong", "gentle", "heavy"],
  },
  {
    name: "Akhal-Teke",
    slug: "akhal-teke",
    category: "light" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 900,
    weightMax: 1000,
    colors: ["golden", "bay", "black", "chestnut", "gray", "palomino", "cremello"],
    distinctiveFeatures: "Distinctive metallic sheen to coat, especially in golden/palomino colors. Lean, athletic build with long neck, refined head, and almond-shaped eyes.",
    overview: "The Akhal-Teke is an ancient breed from Turkmenistan known for its distinctive metallic coat sheen and incredible endurance. One of the oldest and purest breeds, they are prized for their beauty and athletic ability.",
    physicalDescription: "Akhal-Tekes are lean and athletic, standing 14-16 hands with a long, thin neck, refined head, and almond-shaped eyes. Their most distinctive feature is the metallic sheen of their coat, especially pronounced in golden colors.",
    temperament: "Intelligent, spirited, and loyal. Akhal-Tekes bond strongly with one person and can be aloof with strangers. They are sensitive and require patient handling.",
    history: "One of the oldest breeds, developed by Turkmen tribes over 3,000 years ago. Bred for speed and endurance in harsh desert conditions. Remained isolated and pure until recent decades.",
    uses: "Endurance, dressage, show jumping, eventing, and pleasure riding. Their stamina makes them excellent endurance horses.",
    careRequirements: "Require careful management due to their sensitive nature. Their thin skin and fine coat need protection from elements. Bond closely with regular handlers.",
    healthConsiderations: "May carry genes for naked foal syndrome (lethal) and cryptorchidism. Generally healthy but can be sensitive.",
    feedingNotes: "Moderate keepers. Quality nutrition supports their athletic demands. May need more feed than appearance suggests.",
    lifespan: "20-25 years",
    origin: "Turkmenistan",
    popularity: "rare" as const,
    keywords: ["akhal-teke", "metallic", "golden", "endurance", "ancient", "turkmen", "shiny", "athletic"],
  },
  {
    name: "Haflinger",
    slug: "haflinger",
    category: "pony" as const,
    heightMin: 13,
    heightMax: 15,
    weightMin: 800,
    weightMax: 1300,
    colors: ["chestnut", "palomino"],
    distinctiveFeatures: "Always chestnut with flaxen (light) mane and tail. Compact, muscular build with kind expression. Versatile and hardy.",
    overview: "The Haflinger is a versatile Austrian breed known for its distinctive chestnut coat with flaxen mane and tail. Despite their pony size, they are strong enough to carry adults and excel in many disciplines.",
    physicalDescription: "Haflingers are compact and muscular, standing 13-15 hands. They are always chestnut (ranging from light gold to liver) with a flaxen mane and tail. They have a refined head, strong body, and sturdy legs.",
    temperament: "Friendly, willing, and versatile. Haflingers are known for their good temperaments and adaptability. They are intelligent and eager to please.",
    history: "Developed in the Austrian and Italian Alps in the late 1800s. Named after the village of Hafling. Bred for work in mountainous terrain. Now popular worldwide for their versatility.",
    uses: "Driving, trail riding, dressage, jumping, therapeutic riding, and pleasure riding. Their versatility makes them suitable for many disciplines.",
    careRequirements: "Easy keepers requiring standard care. Their thick mane and tail need regular grooming. Hardy and adaptable to various climates.",
    healthConsiderations: "Generally healthy. May be prone to equine metabolic syndrome. Monitor weight carefully.",
    feedingNotes: "Easy keepers prone to obesity. Limited hay and minimal or no grain for most. Monitor grazing carefully.",
    lifespan: "25-30 years",
    origin: "Austria/Italy",
    popularity: "moderate" as const,
    keywords: ["haflinger", "chestnut", "flaxen", "versatile", "alpine", "golden", "sturdy", "pony"],
  },
  {
    name: "Lipizzan",
    slug: "lipizzan",
    category: "warmblood" as const,
    heightMin: 15,
    heightMax: 16,
    weightMin: 1000,
    weightMax: 1300,
    colors: ["gray", "white", "bay"],
    distinctiveFeatures: "Born dark and gradually turn white/gray with age. Compact, powerful build with arched neck and proud carriage. Famous for 'airs above the ground.'",
    overview: "The Lipizzan is famous as the breed of the Spanish Riding School of Vienna, where they perform classical dressage including the spectacular 'airs above the ground.' Born dark, they gradually turn white as they mature.",
    physicalDescription: "Lipizzans are compact and powerful, standing 15-16.1 hands. They have a long head, arched neck, and strong body. Foals are born dark (bay, black, or brown) and gradually turn gray/white, usually by age 6-10.",
    temperament: "Intelligent, willing, and trainable. Lipizzans are known for their calm temperaments and ability to learn complex movements. They are patient and long-lived.",
    history: "Developed in the 16th century at the Lipizza stud (now in Slovenia). Created by crossing Spanish horses with local stock. The Spanish Riding School has performed with Lipizzans since 1572.",
    uses: "Classical dressage, driving, and pleasure riding. Their ability to perform high school movements makes them ideal for classical training.",
    careRequirements: "Standard care with attention to their training needs. Generally hardy and adaptable. Long-lived breed.",
    healthConsiderations: "Generally healthy and long-lived. May be prone to melanomas (common in gray horses) as they age.",
    feedingNotes: "Moderate keepers. Quality hay and appropriate grain maintain condition. Adjust to work level.",
    lifespan: "25-35 years",
    origin: "Slovenia/Austria",
    popularity: "rare" as const,
    keywords: ["lipizzan", "lipizzaner", "white", "gray", "vienna", "spanish riding school", "classical", "dressage"],
  },
  {
    name: "Connemara Pony",
    slug: "connemara-pony",
    category: "pony" as const,
    heightMin: 13,
    heightMax: 15,
    weightMin: 640,
    weightMax: 860,
    colors: ["gray", "dun", "bay", "black", "brown", "chestnut", "roan", "palomino"],
    distinctiveFeatures: "Athletic pony build with good bone, kind eye, and natural jumping ability. Hardy and sure-footed from Irish origins.",
    overview: "The Connemara is Ireland's only native pony breed, known for its athleticism, jumping ability, and hardy nature. Despite their pony size, they excel in competition and can carry adult riders.",
    physicalDescription: "Connemaras are athletic ponies standing 13-15 hands with good bone, a kind eye, and well-sloped shoulders. They have a compact body, strong hindquarters, and hardy constitution. Gray is the most common color.",
    temperament: "Intelligent, willing, and versatile. Connemaras are known for their sensible temperaments and natural athletic ability. They are brave and honest jumpers.",
    history: "Developed in the Connemara region of western Ireland. Influenced by Spanish horses from Armada shipwrecks and later Arabian and Thoroughbred blood. Adapted to harsh Irish conditions.",
    uses: "Jumping, eventing, dressage, driving, and pleasure riding. Their jumping ability makes them popular for children's hunters and ponies.",
    careRequirements: "Hardy and easy keepers. Standard pony care with attention to weight management. Adaptable to various climates.",
    healthConsiderations: "May carry genes for hoof wall separation disease (HWSD). Generally healthy and hardy.",
    feedingNotes: "Easy keepers that can become overweight. Limited hay and minimal grain. Monitor grazing on rich pasture.",
    lifespan: "25-30 years",
    origin: "Ireland",
    popularity: "moderate" as const,
    keywords: ["connemara", "irish", "pony", "jumping", "athletic", "hardy", "gray", "versatile"],
  },
  {
    name: "Standardbred",
    slug: "standardbred",
    category: "light" as const,
    heightMin: 15,
    heightMax: 17,
    weightMin: 900,
    weightMax: 1200,
    colors: ["bay", "brown", "black", "chestnut"],
    distinctiveFeatures: "Athletic build optimized for harness racing. Longer body than Thoroughbreds, powerful hindquarters, and either trotting or pacing gait.",
    overview: "The Standardbred is America's premier harness racing breed, known for their speed at the trot or pace. After racing careers, many become excellent pleasure and sport horses due to their calm temperaments.",
    physicalDescription: "Standardbreds are athletic horses standing 15-17 hands with a longer body than Thoroughbreds, powerful hindquarters, and strong legs. They are either trotters or pacers, depending on their natural gait preference.",
    temperament: "Calm, sensible, and willing. Standardbreds are known for their level-headed temperaments and trainability. Retired racers often make excellent pleasure horses.",
    history: "Developed in America in the 18th century from Thoroughbreds, Morgans, and other breeds. Named because horses had to meet a 'standard' time to be registered. Hambletonian 10 is the foundation sire.",
    uses: "Harness racing, pleasure driving, trail riding, and various riding disciplines. Retired racers are popular for retraining.",
    careRequirements: "Generally easy keepers. Standard care with attention to leg health from racing careers. Adaptable and hardy.",
    healthConsiderations: "Generally healthy. May have leg issues from racing careers. Some may need time to adjust to riding after racing.",
    feedingNotes: "Easy to moderate keepers. Quality hay and appropriate grain. Adjust to activity level.",
    lifespan: "25-30 years",
    origin: "United States",
    popularity: "common" as const,
    keywords: ["standardbred", "harness racing", "trotter", "pacer", "driving", "calm", "athletic", "racehorse"],
  },
  {
    name: "Rocky Mountain Horse",
    slug: "rocky-mountain-horse",
    category: "gaited" as const,
    heightMin: 14,
    heightMax: 16,
    weightMin: 850,
    weightMax: 1000,
    colors: ["chocolate", "bay", "black", "chestnut"],
    distinctiveFeatures: "Distinctive chocolate coat with flaxen mane and tail is the signature color. Smooth four-beat ambling gait. Gentle, willing temperament.",
    overview: "The Rocky Mountain Horse is a gaited breed from Kentucky known for its smooth ambling gait and distinctive chocolate coat with flaxen mane and tail. Despite the name, they originated in the Appalachian Mountains.",
    physicalDescription: "Rocky Mountain Horses stand 14-16 hands with a refined head, arched neck, and well-sloped shoulders. The signature color is chocolate with flaxen mane and tail, though other colors occur. They have a natural four-beat gait.",
    temperament: "Gentle, willing, and people-oriented. Rocky Mountain Horses are known for their calm, sensible temperaments. They are easy to train and handle.",
    history: "Developed in eastern Kentucky in the late 1800s. A stallion named Old Tobe, owned by Sam Tuttle, is considered the foundation sire. The breed was relatively unknown until the 1980s.",
    uses: "Trail riding, pleasure riding, endurance, and showing. Their smooth gait makes them ideal for riders wanting comfortable long rides.",
    careRequirements: "Generally easy keepers. Standard care with attention to their gentle nature. Hardy and adaptable.",
    healthConsiderations: "May carry genes for anterior segment dysgenesis (ASD) causing eye problems. Genetic testing available.",
    feedingNotes: "Easy keepers. Quality hay and limited grain. Monitor for weight gain.",
    lifespan: "25-37 years",
    origin: "United States (Kentucky)",
    popularity: "moderate" as const,
    keywords: ["rocky mountain", "gaited", "chocolate", "flaxen", "smooth", "kentucky", "gentle", "trail"],
  },
  {
    name: "Dutch Warmblood",
    slug: "dutch-warmblood",
    category: "warmblood" as const,
    heightMin: 16,
    heightMax: 17,
    weightMin: 1200,
    weightMax: 1400,
    colors: ["bay", "black", "chestnut", "gray"],
    distinctiveFeatures: "Athletic sport horse build with powerful movement, good temperament, and excellent jumping ability. Bred for international competition.",
    overview: "The Dutch Warmblood (KWPN) is one of the most successful sport horse breeds, excelling in dressage, show jumping, and driving. Developed in the Netherlands, they combine athleticism with trainable temperaments.",
    physicalDescription: "Dutch Warmbloods are athletic horses standing 16-17 hands with powerful hindquarters, good bone, and elastic movement. They are bred in three directions: dressage, jumping, and harness, each with slightly different conformation.",
    temperament: "Intelligent, willing, and athletic. Dutch Warmbloods are known for their trainable temperaments and competitive spirit. They are forward-thinking but manageable.",
    history: "Developed in the Netherlands after WWII by crossing native horses with Thoroughbreds and other warmbloods. The KWPN studbook was founded in 1958. Now one of the most successful breeds in international competition.",
    uses: "Dressage, show jumping, eventing, and driving. They consistently rank among the top breeds in Olympic and World Championship competitions.",
    careRequirements: "Require quality nutrition and regular exercise. Standard sport horse management. May need specialized training.",
    healthConsiderations: "Generally healthy. May be prone to osteochondrosis (OCD) in young horses. Careful breeding practices minimize issues.",
    feedingNotes: "Athletic horses requiring quality nutrition. Hay, grain, and supplements support training demands. Adjust to workload.",
    lifespan: "20-25 years",
    origin: "Netherlands",
    popularity: "common" as const,
    keywords: ["dutch warmblood", "KWPN", "sport horse", "jumping", "dressage", "athletic", "competition", "netherlands"],
  },
  {
    name: "Gypsy Vanner",
    slug: "gypsy-vanner",
    category: "draft" as const,
    heightMin: 13,
    heightMax: 16,
    weightMin: 1100,
    weightMax: 1700,
    colors: ["piebald", "skewbald", "solid"],
    distinctiveFeatures: "Abundant feathering on legs, long flowing mane and tail, and colorful pinto patterns. Compact, powerful build despite smaller size.",
    overview: "The Gypsy Vanner (also called Gypsy Cob or Irish Cob) was developed by Romani people in the British Isles to pull their caravans. Known for their abundant hair, colorful patterns, and gentle temperaments.",
    physicalDescription: "Gypsy Vanners are compact and powerful, standing 13-16 hands. They have abundant feathering on their legs, long flowing manes and tails, and often have pinto (piebald or skewbald) coloring. They have a sweet head and kind eye.",
    temperament: "Gentle, intelligent, and people-oriented. Gypsy Vanners are known for their calm, friendly temperaments. They are easy to handle and train.",
    history: "Developed by Romani people in Britain and Ireland over generations. Bred to pull vardos (caravans) while being gentle enough to be around children. First imported to America in 1996.",
    uses: "Driving, pleasure riding, dressage, and therapeutic riding. Their calm nature and beauty make them popular for many uses.",
    careRequirements: "Require significant grooming to maintain their abundant hair. Feathering needs regular cleaning to prevent skin issues. Generally hardy.",
    healthConsiderations: "May be prone to chronic progressive lymphedema affecting feathered legs. Feathering can harbor bacteria and fungi.",
    feedingNotes: "Easy keepers that can become overweight. Limited hay and minimal grain. Monitor weight carefully.",
    lifespan: "20-25 years",
    origin: "British Isles",
    popularity: "moderate" as const,
    keywords: ["gypsy vanner", "gypsy cob", "feathered", "pinto", "caravan", "romani", "gentle", "colorful"],
  },
];

const horseFactsData = [
  // General Facts
  { title: "Horses Sleep Standing Up", content: "Horses have a unique 'stay apparatus' in their legs that allows them to lock their joints and sleep while standing. This evolved as a survival mechanism, allowing them to flee quickly from predators. However, horses do need to lie down for REM sleep, typically for short periods.", category: "general" as const, audienceLevel: "all" as const },
  { title: "A Horse's Field of Vision", content: "Horses have nearly 360-degree vision due to the placement of their eyes on the sides of their heads. They have two blind spots: directly in front of their nose and directly behind them. This wide field of view helped them survive as prey animals.", category: "general" as const, audienceLevel: "beginner" as const },
  { title: "Horses Cannot Vomit", content: "Due to the angle at which their esophagus connects to their stomach and a strong cardiac sphincter, horses are physically unable to vomit. This makes colic (digestive issues) particularly dangerous for horses.", category: "health" as const, audienceLevel: "all" as const },
  { title: "The Importance of Herd Dynamics", content: "Horses are herd animals with complex social structures. In the wild, herds are typically led by a dominant mare who makes decisions about movement and grazing, while a stallion protects the group. Understanding herd dynamics helps owners manage horses more effectively.", category: "behavior" as const, audienceLevel: "intermediate" as const },
  { title: "Horses Have Excellent Memories", content: "Horses have remarkable long-term memories and can remember people, places, and experiences for many years. They also remember both positive and negative experiences, which is why positive training methods are so important.", category: "behavior" as const, audienceLevel: "all" as const },
  
  // Health Facts
  { title: "Understanding Colic", content: "Colic is the leading cause of death in horses and refers to any abdominal pain. It can range from mild gas pain to life-threatening intestinal twisting. Signs include pawing, rolling, looking at the flank, and refusing to eat. Always call a vet if you suspect colic.", category: "health" as const, audienceLevel: "all" as const },
  { title: "Hoof Health is Crucial", content: "The saying 'no hoof, no horse' reflects how important hoof care is. Horses need regular farrier visits (every 6-8 weeks) for trimming or shoeing. Daily hoof picking removes debris and allows you to check for problems like thrush or abscesses.", category: "care" as const, audienceLevel: "beginner" as const },
  { title: "Dental Care for Horses", content: "Horses' teeth continue to grow throughout their lives and can develop sharp points that cause pain and eating difficulties. Annual dental floats (filing down sharp edges) by an equine dentist are essential for horse health.", category: "health" as const, audienceLevel: "intermediate" as const },
  { title: "Recognizing Laminitis", content: "Laminitis is a painful inflammation of the laminae (tissues connecting the hoof wall to the coffin bone). Signs include reluctance to move, shifting weight, and a 'sawhorse' stance. It can be triggered by grain overload, lush grass, or metabolic issues. Immediate veterinary care is essential.", category: "health" as const, audienceLevel: "intermediate" as const },
  { title: "Parasite Management", content: "Internal parasites can cause serious health issues in horses. Modern parasite management involves fecal egg counts to determine which horses need deworming, rather than routine deworming of all horses. This targeted approach reduces drug resistance.", category: "health" as const, audienceLevel: "advanced" as const },
  
  // Nutrition Facts
  { title: "Horses Need Constant Forage", content: "Horses evolved to graze for 16-18 hours daily. Their digestive systems work best with constant access to forage (hay or pasture). Going long periods without food can lead to ulcers and colic. Slow feeders can help extend eating time.", category: "nutrition" as const, audienceLevel: "beginner" as const },
  { title: "Water Requirements", content: "An average horse drinks 5-10 gallons of water daily, more in hot weather or during exercise. Fresh, clean water should always be available. Horses may reduce water intake if it's too cold, so heated buckets are important in winter.", category: "nutrition" as const, audienceLevel: "beginner" as const },
  { title: "Understanding Hay Quality", content: "Good quality hay should be green, smell fresh, and be free of dust, mold, and weeds. Different types (grass, alfalfa, mixed) have different nutritional profiles. Hay should be the foundation of most horses' diets.", category: "nutrition" as const, audienceLevel: "intermediate" as const },
  { title: "The Danger of Grain Overload", content: "Horses' digestive systems are designed for forage, not grain. Too much grain can cause colic, laminitis, and other serious issues. If grain is needed, it should be fed in small amounts spread throughout the day.", category: "nutrition" as const, audienceLevel: "intermediate" as const },
  { title: "Salt and Mineral Needs", content: "Horses need salt daily and should have access to a salt block or loose salt. Additional minerals may be needed depending on local soil and forage. A balanced vitamin-mineral supplement can fill nutritional gaps.", category: "nutrition" as const, audienceLevel: "intermediate" as const },
  
  // Behavior Facts
  { title: "Reading Horse Body Language", content: "Horses communicate through body language. Ears forward indicate interest, ears pinned back signal aggression or discomfort. A relaxed horse has soft eyes and a lowered head. Learning to read these signals improves safety and communication.", category: "behavior" as const, audienceLevel: "beginner" as const },
  { title: "Why Horses Spook", content: "Horses are prey animals with strong flight instincts. They may spook at unfamiliar objects, sudden movements, or sounds. Understanding this helps riders stay calm and redirect the horse's attention rather than punishing natural behavior.", category: "behavior" as const, audienceLevel: "beginner" as const },
  { title: "The Importance of Routine", content: "Horses thrive on routine and can become stressed by sudden changes. Consistent feeding times, turnout schedules, and handling help horses feel secure. When changes are necessary, introduce them gradually.", category: "behavior" as const, audienceLevel: "all" as const },
  { title: "Understanding Horse Play", content: "Horses play by running, bucking, rearing, and mock-fighting. Play is important for physical and mental health, especially in young horses. Adequate turnout time with compatible companions allows natural play behavior.", category: "behavior" as const, audienceLevel: "intermediate" as const },
  { title: "Stereotypic Behaviors", content: "Behaviors like cribbing, weaving, and stall walking are often called 'vices' but are actually coping mechanisms for stress. They often develop from inadequate turnout, social isolation, or other management issues. Prevention is better than cure.", category: "behavior" as const, audienceLevel: "advanced" as const },
  
  // Training Facts
  { title: "Pressure and Release", content: "Horses learn primarily through the release of pressure. When a horse responds correctly, immediately releasing pressure rewards the behavior. This is the foundation of most training methods and is how horses naturally communicate.", category: "training" as const, audienceLevel: "beginner" as const },
  { title: "The Value of Groundwork", content: "Groundwork (working with a horse from the ground) builds respect, communication, and trust before riding. It's also useful for horses that can't be ridden due to age, injury, or training level.", category: "training" as const, audienceLevel: "beginner" as const },
  { title: "Consistency in Training", content: "Horses learn best with consistent cues and expectations. All handlers should use the same commands and methods. Inconsistency confuses horses and can create behavioral problems.", category: "training" as const, audienceLevel: "intermediate" as const },
  { title: "Understanding Flight Response", content: "When frightened, a horse's first instinct is to flee. Training helps horses learn to look to their handler for guidance instead of fleeing. Building trust and confidence takes time but creates a safer, more reliable partner.", category: "training" as const, audienceLevel: "intermediate" as const },
  { title: "The Learning Process", content: "Horses learn through repetition and positive associations. Short, frequent training sessions are more effective than long, infrequent ones. Always end on a positive note, even if it means going back to something the horse knows well.", category: "training" as const, audienceLevel: "all" as const },
  
  // History Facts
  { title: "Evolution of the Horse", content: "Modern horses evolved from a small, dog-sized forest dweller called Eohippus (or Hyracotherium) about 55 million years ago. Over millions of years, they grew larger and adapted to grassland environments.", category: "history" as const, audienceLevel: "all" as const },
  { title: "Horses in Human History", content: "Horses were domesticated around 4000 BCE on the steppes of Central Asia. They revolutionized transportation, warfare, and agriculture, fundamentally changing human civilization.", category: "history" as const, audienceLevel: "all" as const },
  { title: "The Arabian Influence", content: "The Arabian horse is one of the oldest breeds and has influenced nearly every modern light horse breed. Their genetics can be found in Thoroughbreds, Quarter Horses, Morgans, and many others.", category: "history" as const, audienceLevel: "intermediate" as const },
  { title: "Horses in America", content: "Horses evolved in North America but went extinct about 10,000 years ago. Spanish conquistadors reintroduced horses in the 1500s. Some escaped to form wild herds, while others were acquired by Native American tribes.", category: "history" as const, audienceLevel: "all" as const },
  { title: "The Decline of Working Horses", content: "Before mechanization, horses powered agriculture, transportation, and industry. The transition to tractors and automobiles in the early 1900s dramatically reduced horse populations. Today, horses are primarily kept for recreation and sport.", category: "history" as const, audienceLevel: "intermediate" as const },
  
  // Care Facts
  { title: "Daily Horse Care Basics", content: "Basic daily care includes feeding, providing fresh water, checking for injuries, and cleaning hooves. Horses should be observed for changes in behavior, appetite, or movement that might indicate health issues.", category: "care" as const, audienceLevel: "beginner" as const },
  { title: "Grooming Benefits", content: "Regular grooming does more than keep horses clean. It improves circulation, distributes natural oils, allows you to check for injuries or skin issues, and strengthens the bond between horse and handler.", category: "care" as const, audienceLevel: "beginner" as const },
  { title: "Shelter Requirements", content: "Horses need protection from extreme weather. A three-sided shelter (run-in shed) provides relief from sun, wind, and precipitation. Stalls should be well-ventilated, dry, and large enough for the horse to move and lie down comfortably.", category: "care" as const, audienceLevel: "beginner" as const },
  { title: "Turnout Importance", content: "Horses need daily turnout for physical and mental health. Movement aids digestion, maintains joint health, and allows natural behaviors. Horses kept in stalls without adequate turnout often develop behavioral and health problems.", category: "care" as const, audienceLevel: "intermediate" as const },
  { title: "Seasonal Care Considerations", content: "Horse care needs change with seasons. Summer requires fly control and sun protection. Winter needs include ensuring water doesn't freeze and providing adequate calories for warmth. Spring brings concerns about lush grass and laminitis.", category: "care" as const, audienceLevel: "intermediate" as const },
];

async function seed() {
  console.log("Seeding breeds...");
  
  for (const breed of breedData) {
    try {
      await db.insert(breeds).values(breed).onDuplicateKeyUpdate({
        set: { ...breed, updatedAt: new Date() }
      });
      console.log(`  ✓ ${breed.name}`);
    } catch (error) {
      console.error(`  ✗ ${breed.name}:`, error);
    }
  }
  
  console.log("\nSeeding horse facts...");
  
  for (const fact of horseFactsData) {
    try {
      await db.insert(horseFacts).values(fact);
      console.log(`  ✓ ${fact.title}`);
    } catch (error) {
      console.error(`  ✗ ${fact.title}:`, error);
    }
  }
  
  console.log("\nSeeding complete!");
  process.exit(0);
}

seed().catch(console.error);
